const data = {
    products:[
        {
            _id: '1',
            name: 'Lightweight Sweatshirt',
            category: 'Sweatshirt',
            image: '/images/p1.png',
            rating: 4.0,
            price: 40,
            description: 'Great for running in cool temps',
            brand: 'Cramazon',
            numreviews: 11,
        },
        {
            _id: '2',
            name: 'Under Armor Sweatshirt',
            category: 'Sweatshirt',
            image: '/images/p2.png',
            rating: 4.3,
            price: 50,
            description: 'Great for all-around use',
            brand: 'Under Armor',
            numreviews: 21,
        },
        {
            _id: '3',
            name: 'Nike Sweatshirt',
            category: 'Sweatshirt',
            image: '/images/p3.png',
            rating: 4.8,
            price: 90,
            description: 'Great for running in cool temps',
            brand: 'Nike',
            numreviews: 40,
        },
        {
            _id: '4',
            name: 'Heavy Jacket',
            category: 'Jacket',
            image: '/images/p4.png',
            rating: 3.4,
            price: 400,
            description: 'Great for freezing temps',
            brand: 'Cramazon',
            numreviews: 166,
        },
        {
            _id: '5',
            name: 'Lightweight Pants',
            category: 'Pants',
            image: '/images/p5.png',
            rating: 4.2,
            price: 80,
            description: 'Great for running in cool temps',
            brand: 'Cramazon',
            numreviews: 27,
        },
        {
            _id: '6',
            name: 'T-Shirt',
            category: 'Shirt',
            image: '/images/p6.png',
            rating: 4.9,
            price: 20,
            description: 'Great for everything',
            brand: 'Cramazon',
            numreviews: 100,
        },
    ],
};
export default data